# Generated by Django 3.1 on 2020-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Gowns',
        ),
    ]
